version: '3.9'

services:
  nuxt3:
    container_name: nuxt3
    build: docker/nuxt3
    volumes:
      - ./app:/app:cached
      - ./app/node_modules:/app/node_modules
    working_dir: "/app"
    ports:
      - 3000:3000
      - 24678:24678
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn install && yarn dev -o"
